name: Coninuous Integration
on: [push]
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-cache
    
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
    
      - name: Install Dependencies
        run: cd backend && npm i

      - name: Build
        run: cd backend && npm run build

      - name: Generate Artifact
        run: cd backend/build && zip -r artifact.zip ./ -x '*.git*' 

      - name: Store Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: backend-artifact
          path: backend/build/artifact.zip

  lint:
      needs: [Compile]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v1
          
        - name: Cache Node Modules
          id: cache
          uses: actions/cache@v4
          with:
           path: node_modules
           key: node_modules-cache
        
        - name: Install Dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: cd backend && npm i

        - name: Lint the code
          run: cd backend && npm run lint

  test:
      needs: [Compile] 
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Cache Node Modules
          id: cache
          uses: actions/cache@v4
          with:
           path: node_modules
           key: node_modules-cache 

        - name: Install Dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: cd backend && npm i

        - name: Run unit tests
          run: cd backend && npm t

        
  security-audit:
    needs: [Compile]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check for security issue
        run: cd backend && npm audit --audit-level=medium
        