name: Coninuous Integration
on: [push]
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-cache
    
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
    
      - name: Build
        run: cd backend && npm run build

      - name: Generate Artifact
        run: cd backend/build && zip -r artifact.zip ./ -x '*.git*' 

      - name: Store Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: backend-artifact
          path: backend/build/artifact.zip

    