name: Coninuous Integration
on: [push]
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: cd backend && npm i
      - run: cd backend && npm run build
    